name: Auto-Add to Project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: Add to Project
      run: |
        # Set your project name
        project_name="@Zgallagher729's ooptroop"
        # Add the issue to the project using gh
        gh issue edit ${{ github.event.issue.number }} --add-project "$project_name"
